### ISSUE TITLE
GSAP and framer-motion-3d animations don't work

### ISSUE THREAD

**Issue by meesrutten** [pmndrs/xr#180]
We've been building a VR game with `@react-three/vr` which is an absolute blast.
We have found some issues where GSAP and framer-motion-3d don't work.
That may be because they use requestAnimationFrame, but we're not sure.

Does anyone know why this doesn't work and can we help to fix this? :)

**Comment by saitonakamura** [comment]
The problem is most certainly the rAF. When browser enters an immersive session it will (I don't remember if all of them do or the certain ones, like Oculus Browser) stop the rAF (in workers also) and you'll have to rely on session frame callback to do stuff. Animation frameworks and libs usually have a safehatch to trigger the update from the outside, that's were you need to dig. For instance here how it's done in `@react-spring/three`, https://github.com/pmndrs/react-spring/blob/master/targets/three/src/index.ts#L18
For a vr session you can use `useFrame` for r3f 8+ or `useXREvent` for older ones

**Comment by saitonakamura** [comment]
@meesrutten does that ^ helps?

**Comment by bbohlender** [comment]
As mentioned by @mattrossman, frame-motion and gsap seem to not support using the animation frame callback provided by the platform (e.g. through `useFrame`). A working alternative animation library is react-spring.

This issue is not related to the implementation of this library, but a underlying issue of frame motion and gsap because they use requestAnimationFrame which shouldn't be used in WebXR contexts, since WebXR provides [its own frameloop](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Rendering#preparing_the_renderer).

**Comment by mattrossman** [comment]
Note that it's only framer-motion that has this limitation, with GSAP you can unhook the default ticker and manually update its time inside `useFrame()` to get it working in WebXR.

https://gsap.com/docs/v3/GSAP/gsap.updateRoot()/

**Comment by bbohlender** [comment]
@mattrossman awesome 🎉
Thanks for the clarification  🙏🏼
