### ISSUE TITLE
First person setup with physics

### ISSUE THREAD

**Issue by dreammonkey** [pmndrs/xr#211]
Hey,

I've created a basic setup in which I created a first person controller and added physics to it.
The demo works fine. But I believe my setup might be entirely wrong.

Right now moving around using the controllers works well (left controller for moving, right controller for rotating).
But when turning your head or your entire body the experience is wrong and directions no longer correlate with reality.

It is also possible to walk away from / step out of the physics collider ... Right now the player object is being put at the position of the collider every frame. But maybe the collider should be put inside of the player group ? All this is a bit confusing. 

As these are my first steps in VR (and rapier) I'm mostly looking for some pointers. Any advice is much appreciated !

Here is the link to the sandbox:
https://codesandbox.io/s/r3f-xr-rapier-first-person-2uxdyb?file=/src/components/RapierScene.tsx

**Comment by bbohlender** [comment]
You are describing a conceptually difficult problem since the the players position in the world is now controlled by 3 different inputs (physics, gamepad, and the users position).

I'll try to propose a solution, but I recommend looking at games/apps with the same setup to see how they solve it (e.g. by testing out the edge cases when standing near a cliff if the player falls down if they move themselves without using the gamepad).

My proposed solution:
Sync the Physics collider's bottom position plus with the player origin.

**Comment by bbohlender** [comment]
You are describing a conceptually difficult problem since the player’s position in the world is now controlled by three different inputs (physics, gamepad, and the user’s position).
I recommend looking at games/apps with the same problem to see how they solve it (e.g. by testing out the edge cases when standing near a cliff if the player falls down if they move themselves without using the gamepad). In general you want to figure out how you want to map the user’s movements to the physical collider, while also allowing the collider to move on its own, which will influence the players position. There is no clear source of truth here because both influence each other.

If you find a game that solves this in a, for you, acceptable way, I can try to assist rebuilding that behavior :)
