### ISSUE TITLE
Possibility of Video or I-Frame embed in React XR

### ISSUE THREAD

**Issue by iamkkt** [pmndrs/xr#214]
As per my understanding, Drei Html component wont render in react XR and Drei Image component wont support video. Is there is any work around for I- Frame or Video embeed in react XR.

**Comment by CodyJasonBennett** [comment]
I'd look into projecting a [`VideoTexture`](https://threejs.org/docs/#api/en/textures/VideoTexture) onto a plane or adding support for that in [pmndrs/drei#image](https://github.com/pmndrs/drei#image) if it doesn't already. It should be fine as long as it doesn't rely on `window.requestAnimationFrame` -- this does not with in an immersive session.

**Comment by iamkkt** [comment]
Thank you for replies. I have tried with video texture and works fine for video. As the size of the video increases, it might create a problem for as it cant stream. Is there any work around for this, where i can able to stream like youtube or any possibility of YouTube embed in react XR like drei html ?

**Comment by iamkkt** [comment]
My requirement is to stream either a video of length 30 min or a YouTube video.

**Comment by rgsaura** [comment]
Hello! Exited to explore this field. What about inserting an Iframe, any idea?

**Comment by rekliner** [comment]
This issue is not related to react-XR.
https://github.com/pmndrs/drei#usevideotexture is your answer for displaying video from a file or stream.  

To get video content from a service like youtube or vimeo requires reverse engineering their player, something they explicitly make difficult.  By design you can't directly access their video content, and there is no out of box solution.  Any method that is popularized is quickly obfuscated in response by those companies and their methods are proprietary.

Regardless, it would happen outside of the realm of react-xr, drei, and three.js.  Nothing can be done here to help you.  Once you have the video stream available useVideoTexture() is your resource here.

**Comment by netgfx** [comment]
On a similar note a simple mp4 video is playing fine, until entering the AR mode a second time then the video stops, and any subsequent try to enter AR the video stops immediately. Is there a limitation or something that needs to be enabled in order for the video to work every time someone enters AR mode?

**Comment by bbohlender** [comment]
> Hello! Exited to explore this field. What about inserting an Iframe, any idea?

Iframes do not work. Check out [uikit](https://github.com/pmndrs/uikit) for this use case.

> until entering the AR mode a second time then the video stops, and any subsequent try to enter AR the video stops immediately

@netgfx 
Can you check if that behavior persists with react-three/xr v6 and the latest Quest Browser (or whatever browser + device you are using) since I have not yet experienced this behavior. If so, please open another issue related to that :)
